# Generated by Django 3.1.14 on 2024-10-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20241002_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disappeared',
            new_name='disappeared_at',
        ),
    ]
