# Generated by Django 3.1.14 on 2024-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
